import {test,expect} from '@playwright/test';
test('admin workflow, public forms, search and responsive School Land pages',async({page})=>{
  await page.addInitScript(()=>sessionStorage.setItem('prism-principals-school-leadership-award-seen','true'));
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto('/admin');
  await expect(page).toHaveURL(/admin\/login/);
  await page.getByLabel('Email or username').fill('browser-admin');
  await page.getByLabel('Password',{exact:true}).fill('wrong');
  await page.getByRole('button',{name:'Login',exact:true}).click();
  await expect(page.getByRole('alert')).toContainText('Invalid');
  await page.getByLabel('Password',{exact:true}).fill('browser-test-only-password');
  await page.getByRole('button',{name:'Show password'}).click();
  await expect(page.getByLabel('Password',{exact:true})).toHaveAttribute('type','text');
  await page.getByRole('button',{name:'Login',exact:true}).click();
  await expect(page).toHaveURL(/admin\/school-land/);
  await page.getByRole('button',{name:'Add New Land Listing'}).click();
  await page.getByLabel('Listing title').fill('Pune Learning Campus');
  await page.getByLabel('Complete / required location').fill('Ravet, Pune');
  await page.getByLabel(/^City/).fill('Pune');
  await page.getByLabel(/^State/).fill('Maharashtra');
  await page.getByLabel('Available / required area').fill('4000');
  await page.getByLabel('Full property description / detailed requirement').fill('A spacious campus with school bus access.');
  await page.getByRole('combobox',{name:'Approval status',exact:true}).selectOption('Approved');
  await page.getByRole('combobox',{name:'Admin status',exact:true}).selectOption('Active');
  await page.getByRole('combobox',{name:'Publication status',exact:true}).selectOption('Published');
  await page.getByLabel('Feature on Home page').check();
  await page.getByLabel('Upload images').setInputFiles('tmp/test-property.png');
  await page.getByRole('button',{name:'Save Listing'}).click();
  await expect(page.getByRole('heading',{name:'Pune Learning Campus'})).toBeVisible();
  await page.goto('/');
  await expect(page.getByRole('heading',{name:'Pune Learning Campus'})).toBeVisible();
  await page.goto('/school-land');
  await expect(page.getByText('Showing 1 listing',{exact:true})).toBeVisible();
  await page.getByLabel('Keyword search').fill('nothing-matches');
  await page.getByRole('button',{name:'Search',exact:true}).click();
  await expect(page.getByText('No matching School Land listings found.')).toBeVisible();
  await page.getByRole('button',{name:'Clear Filters',exact:true}).first().click();
  await expect(page.getByText('Showing 1 listing',{exact:true})).toBeVisible();
  await page.getByRole('heading',{name:'Pune Learning Campus'}).click();
  await expect(page.getByRole('heading',{name:'Pune Learning Campus'})).toBeVisible();
  await page.reload();
  await expect(page.getByText('4,000').or(page.getByText('4000 sq. ft.',{exact:true}))).toBeVisible();
  for(const [width,height,label] of [[1440,1000,'desktop'],[768,1024,'tablet'],[320,900,'mobile']]){
    await page.setViewportSize({width,height});await page.goto('/school-land');
    await page.getByRole('heading',{name:'Pune Learning Campus'}).waitFor();
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
    await page.locator('#school-land-listings').screenshot({path:'tmp/land-'+label+'.png'});
  }
  await page.setViewportSize({width:1280,height:1000});
  await page.goto('/school-land/requirement');
  await page.getByLabel('Available / required area').fill('5000');
  await page.getByRole('button',{name:'Submit for Admin Review'}).click();
  await expect(page.getByText('Please correct the highlighted fields above.')).toBeVisible();
  await page.getByLabel('Complete / required location').fill('Wakad, Pune');
  await page.getByLabel(/^City/).fill('Pune');
  await page.getByLabel(/^State/).fill('Maharashtra');
  await page.getByLabel('Available / required area').fill('5000');
  await page.getByLabel('Full property description / detailed requirement').fill('Need a school campus on lease.');
  await page.getByLabel('Applicant / contact-person name').fill('Browser Applicant');
  await page.getByLabel(/^Phone number/).fill('9876543210');
  await page.getByLabel('Email address').fill('applicant@example.test');
  await page.getByLabel(/I consent/).check();
  await page.getByRole('button',{name:'Submit for Admin Review'}).click();
  await expect(page.getByRole('heading',{name:'Submission saved'})).toBeVisible();
  await expect(page.getByRole('link',{name:'Send Details on WhatsApp'})).toHaveAttribute('href',/https:\/\/wa.me\/919518963309/);
  await page.goto('/admin/school-land');
  await page.getByRole('button',{name:'Review User Submissions'}).click();
  await expect(page.getByRole('heading',{name:'School Land Requirement',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Manage Land Listings',exact:true}).click();
  let card=page.locator('.land-admin-record').filter({has:page.getByRole('heading',{name:'Pune Learning Campus'})});
  await card.getByRole('button',{name:'Edit',exact:true}).click();
  await page.getByLabel('Keep completed listing visible').check();
  await page.getByRole('combobox',{name:'Deal status',exact:true}).selectOption('Sold');
  await page.getByRole('button',{name:'Save Listing'}).click();
  await expect(page.getByText('Changes saved.',{exact:true})).toBeVisible();
  await page.goto('/school-land');
  await expect(page.getByText('No matching School Land listings found.')).toBeVisible();
  await page.goto('/');
  await expect(page.locator('.land-card .land-completed')).toHaveText('SOLD OUT');
  await page.goto('/admin/school-land');
  await page.getByRole('button',{name:'Logout',exact:true}).click();
  await expect(page).toHaveURL(/admin\/login/);
  await page.goto('/admin/school-land');
  await expect(page).toHaveURL(/admin\/login/);
  expect(errors).toEqual([]);
});


