import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import ClientsSection from './ClientsSection';
import './about-leadership.css';
import {ArrowRight,Award,BadgeCheck,BookOpen,ChevronLeft,ChevronRight,Code2,Eye,FileText,FlaskConical,Handshake,HeartHandshake,LandPlot,Lightbulb,Scale,School,ShieldCheck,Sprout,Target,Users,X} from 'lucide-react';

const aboutNav=[['Our Founder','about-founder'],['Our Team','about-team'],['Our Partners','about-partners'],['Our Values','about-values'],['Our Clients','about-clients']];
const team=[
  {"name":"Dr. Prajkta Shinde","role":"Founder and Director","image":"/images/prism-official/founder-dr-prajkta-shinde.jpg","bio":["Dr. Prajkta Shinde is an experienced educationist and academic leader with more than 23 years of experience in education. She holds M.Ed., B.Ed., D.Ed., PGDTT from Symbiosis and B.Sc. in Chemistry, and is currently pursuing her Ph.D. in Education.","Her professional journey includes roles as Academic Director, Principal, Supervisor, Coordinator, Auditor and Trainer, with experience across K–12 establishment, planning, curriculum, school management, licensing, branding and institutional development.","Through Prism Edu, she brings together professionals from education, administration, infrastructure, technology and allied sectors to provide coordinated, practical support. Her leadership approach centres on understanding each institution’s context, strengthening academic and operational foundations and helping education promoters move forward with clarity."],"expertise":["Educational Leadership","Institutional Development","School Planning & Support","Vision-led Guidance"],"quote":"“Every educational vision deserves thoughtful planning, responsible guidance and the right professional support to grow into a meaningful institution.”","badge":"23+ Years in Education"},
  {name:'Dr. P. R. Badadapure',role:'Co-Founder and Chief Administrative Officer',image:'/images/prism-official/dr-pr-badadapure.jpeg',intro:'An experienced academician, administrator and education professional with 33 years of teaching experience.',bio:[
    'Dr. P. R. Badadapure currently serves as Dean – Administration & Human Resource at Pimpri Chinchwad Education Trust (PCET), Akurdi, Pune.',
    'He holds a Ph.D. in Electronics and Communication Engineering, a Master of Engineering from Walchand College of Engineering, Sangli, and a Bachelor of Engineering from Walchand Institute of Technology, Solapur. During his career, he has served as Principal, Professor, Assistant Professor and Lecturer across engineering and educational institutions.',
    'His experience in academic leadership, human resources, institutional administration, teaching, research and innovation brings practical insight to Prism Edu’s work with educational institutions. His academic contributions include research publications and patent publications in emerging engineering and technology areas.'
  ],expertise:['Academic leadership','Institutional administration','Human resources','Teaching, research & innovation']},
  {name:'Prof. Madhukar D. Takale',role:'Strategic Advisor and Institutional Development',image:'/images/prism-official/prof-madhukar-takale.jpeg',intro:'An experienced educationist, electrical engineering professional, administrator and entrepreneur with over 34 years of experience.',bio:[
    'Prof. Madhukar D. Takale holds an M.E. in Electrical Engineering (Power Systems) and has worked in positions ranging from Design Engineer and Lecturer to Assistant Professor, Professor and Director (Administration) of JSPM Group of Institutes, Pune.',
    'His experience includes establishing and developing professional educational institutions in engineering, pharmacy, MBA, MCA and medical education, together with educational campus development, e-learning solutions, educational equipment manufacturing and engineering enterprises.',
    'At Prism Edu, his academic, administrative, technical and institutional-development experience supports education promoters and institutions in planning and strengthening their educational projects.'
  ],expertise:['Institutional development','Academic administration','Campus planning','Technical education']},
];
const values=[[ShieldCheck,'Integrity & Transparency','Clear communication and guidance grounded in genuine institutional requirements.'],[BookOpen,'Education First','Academic quality, responsible practice and student development remain central.'],[Target,'Practical Guidance','Realistic and implementable support without unnecessary complexity.'],[Handshake,'Collaboration','Progress through cooperation among promoters, educators and professionals.'],[Lightbulb,'Innovation','Thoughtful technology for education, administration and communication.'],[Sprout,'Responsible Growth','Systems and practices designed to support long-term institutional development.']];
const gallery=[['/images/prism-official/school-workshop.jpg','Workshops & Training'],['/images/prism-official/school-community.jpg','School Community Engagement'],['/images/events-awards/india-k12-awards-2025.jpg','Professional Recognition'],['/images/events-awards/education-conclave-recognition.jpg','Education Leadership Recognition']];

function Lightbox({item,onClose,onMove}){useEffect(()=>{if(!item)return;const key=e=>{if(e.key==='Escape')onClose();if(e.key==='ArrowLeft')onMove(-1);if(e.key==='ArrowRight')onMove(1)};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)},[item,onClose,onMove]);if(!item)return null;return <div className="fixed inset-0 z-[100] grid place-items-center bg-black/90 p-4" role="dialog" aria-modal="true" aria-label={item[1]}><button onClick={onClose} className="absolute right-5 top-5 grid h-11 w-11 place-items-center rounded-full bg-white/10 text-white" aria-label="Close gallery"><X/></button><button onClick={()=>onMove(-1)} className="absolute left-3 grid h-11 w-11 place-items-center rounded-full bg-white/10 text-white md:left-8" aria-label="Previous image"><ChevronLeft/></button><figure className="max-w-5xl"><img src={item[0]} alt={item[1]} className="max-h-[78vh] w-auto rounded-xl object-contain"/><figcaption className="mt-4 text-center font-semibold text-white">{item[1]}</figcaption></figure><button onClick={()=>onMove(1)} className="absolute right-3 grid h-11 w-11 place-items-center rounded-full bg-white/10 text-white md:right-8" aria-label="Next image"><ChevronRight/></button></div>}
function SectionTitle({eyebrow,title,text}){return <div className="mx-auto max-w-4xl text-center"><p className="section-kicker">{eyebrow}</p><h2 className="section-heading">{title}</h2>{text&&<p className="mx-auto mt-5 max-w-3xl leading-8 text-slate-600">{text}</p>}</div>}

export default function AboutRedesign(){
  const[active,setActive]=useState('about-founder'),[photo,setPhoto]=useState(null);
  useEffect(()=>{const update=()=>document.documentElement.style.setProperty('--about-header-height',(document.querySelector('header')?.offsetHeight||0)+'px');update();addEventListener('resize',update);const observer=new IntersectionObserver(entries=>{const visible=entries.filter(entry=>entry.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(visible)setActive(visible.target.id)},{rootMargin:'-32% 0px -55%',threshold:[0,.15,.35]});aboutNav.forEach(([,id])=>{const element=document.getElementById(id);if(element)observer.observe(element)});const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');revealObserver.unobserve(entry.target)}}),{threshold:.08});document.querySelectorAll('.about-anchor-section>.wrap,.about-introduction>.wrap').forEach(element=>{element.classList.add('about-reveal');revealObserver.observe(element)});return()=>{removeEventListener('resize',update);observer.disconnect();revealObserver.disconnect();document.documentElement.style.removeProperty('--about-header-height')}},[]);
  const movePhoto=n=>setPhoto(i=>(i+n+gallery.length)%gallery.length);
  return <div className="about-page-redesign">
    <nav className="about-sticky-nav" aria-label="About page sections"><div>{aboutNav.map(([label,id])=><a key={id} href={'#'+id} className={active===id?'is-active':''} aria-current={active===id?'true':undefined}>{label}</a>)}</div></nav>

    <section className="about-introduction"><div className="wrap"><div className="about-intro-grid"><div><p className="section-kicker">ABOUT PRISM EDU</p><h1>About Prism Edu Consultancy</h1><p>Prism Edu Consultancy is an education-focused support platform created to help schools, educational institutions, school promoters, entrepreneurs, landowners, vendors and professional service providers connect with practical resources and guidance.</p><p>Our coordinated ecosystem supports new-school planning, establishment and incubation, licensing and affiliation coordination, administration, academic improvement, branding, admissions, digital solutions, school land and school-material networking.</p><p>Prism connects schools and education professionals with property owners, vendors, technology partners and other relevant stakeholders so that different institutional requirements can be understood and supported through one coordinated professional network.</p><div className="about-intro-actions"><Link to="/services" className="btn">Explore Our Services</Link><Link to="/contact?enquiry=consultation" className="btn2">Request Consultation</Link></div></div><div className="about-support-grid">{[['Who We Are','A multidisciplinary education-support platform.'],['What We Support','Planning, academics, operations, property, compliance, technology and growth.'],['Who We Work With','Promoters, schools, trusts, educators, landowners, vendors and entrepreneurs.'],['Our Approach','Practical, coordinated and specific to each institution’s requirements.']].map(([title,text])=><article key={title}><h2>{title}</h2><p>{text}</p></article>)}</div></div></div></section>


    <section id="about-founder" className="about-anchor-section bg-[#f4f7fa] py-16 md:py-24"><div className="wrap"><div id="about-team" className="about-anchor-section"><SectionTitle eyebrow="OUR LEADERSHIP" title="Experience • Expertise • Collaboration" text="Prism Edu brings together professionals with experience across education, academic leadership, institutional administration, technology, infrastructure and digital transformation. Our multidisciplinary approach helps us understand educational projects from different perspectives and provide coordinated support based on each institution’s requirements."/></div><div className="about-team-grid about-leadership-grid">{team.map(person=><article key={person.name} className="about-detailed-profile"><img src={person.image} alt={person.name} loading="lazy"/><div><h3>{person.name}</h3><strong>{person.role}</strong>{person.badge&&<p className="about-profile-intro">{person.badge}</p>}{person.intro&&<p className="about-profile-intro">{person.intro}</p>}<div className="about-profile-copy">{person.bio.map(paragraph=><p key={paragraph}>{paragraph}</p>)}</div><div className="about-expertise-list">{person.expertise.map(item=><span key={item}>{item}</span>)}</div>{person.quote&&<blockquote className="mt-5 border-l-2 border-[#eeb640] pl-4 text-sm leading-7 text-slate-600">{person.quote}</blockquote>}</div></article>)}</div></div></section>

    <section id="about-partners" className="about-anchor-section about-partners-section"><div className="wrap"><SectionTitle eyebrow="OUR PARTNERS" title="Growing Through Professional Collaboration" text="Prism Edu works with complementary professional disciplines to support educational institutions responsibly and practically."/><div className="about-partner-grid"><article><FlaskConical/><h3>Robotics & STEM Partner</h3><p>Support across robotics education, STEM learning, innovation labs, coding exposure and activity-based teacher and student workshops.</p><small>Partner identity will be published after verification.</small></article><article><Scale/><h3>Legal Partner</h3><p>Professional support for documentation coordination, registration-related guidance, compliance, policies, agreements and education-related legal requirements.</p><small>Partner identity will be published after verification. Prism Edu is not a law firm.</small></article><article className="digital-partner"><img src="/images/prism-official/yogini-pawar.jpeg" alt="Yogini Pawar, Web and Digital Solutions Partner" loading="lazy"/><Code2/><h3>Yogini Pawar</h3><strong>Web & Digital Solutions Partner</strong><p>Yogini Pawar is a young entrepreneur specializing in web development and digital solutions, with approved project content documenting experience across more than 20 projects. She supports schools, educational institutions and startups with practical and affordable technology solutions.</p><p>Her work includes websites, custom web applications, mobile applications, school systems, workflow automation, digital marketing, social media, SEO, branding and technical support.</p><Link to="/contact?service=web-digital">Discuss a Digital Project<ArrowRight size={16}/></Link></article></div></div></section>

    <section id="about-values" className="about-anchor-section bg-white py-16 md:py-24"><div className="wrap"><SectionTitle eyebrow="OUR VALUES" title="The Principles That Guide Our Work"/><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{values.map(([Icon,title,text])=><article key={title} className="value-card"><Icon/><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>

    <ClientsSection/>

    <section className="relative overflow-hidden bg-[#10263f] py-16 text-white md:py-20"><div className="wrap grid gap-6 lg:grid-cols-2"><article className="about-feature-card dark"><Eye/><h2>Our Vision</h2><h3>Empowering Educational Institutions for Sustainable Growth</h3><p>To support educational institutions through strategic guidance, practical solutions, responsible technology and collaborative partnerships.</p></article><article className="about-feature-card dark"><HeartHandshake/><h2>Our Mission</h2><h3>Supporting Education with Purpose</h3><p>We work alongside schools, trusts, societies, promoters and education entrepreneurs across planning, academics, administration, infrastructure, compliance and growth.</p></article></div></section>
    <section className="bg-[#f4f7fa] py-16 md:py-24"><div className="wrap"><SectionTitle eyebrow="WHY PRISM EDU?" title="One Platform. Multiple Areas of Educational Support." text="We bring together school education, academic leadership, administration, infrastructure, compliance and technology within a coordinated consultancy platform."/><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['23+','Founder’s Education Experience'],['33','Academic & Institutional Experience'],['34+','Education & Administration Experience'],['20+','Web & Digital Solutions Projects']].map(([number,label])=><article key={label} className="rounded-2xl bg-white p-6 text-center shadow-sm"><strong className="text-4xl font-extrabold text-[#10263f]">{number}</strong><p className="mt-2 text-sm font-semibold text-slate-600">{label}</p></article>)}</div><p className="mx-auto mt-6 max-w-3xl text-center text-xs leading-5 text-slate-500">These figures represent the individual professional experience of respective team members and do not represent Prism Edu’s operating history.</p></div></section>
    <section className="bg-[#f7f0e3] py-16 md:py-24"><div className="wrap"><SectionTitle eyebrow="AWARDS & ACHIEVEMENTS" title="Recognising Professional Excellence" text="Verified professional recognition photographs supplied by Prism Edu."/><div className="mt-9 grid gap-5 md:grid-cols-2">{gallery.slice(2).map(([src,alt],index)=><button key={src} onClick={()=>setPhoto(index+2)} className="award-card text-left"><img src={src} alt={alt} loading="lazy"/><span>{alt}</span></button>)}</div></div></section>
    <section className="bg-white py-16 md:py-24"><div className="wrap"><SectionTitle eyebrow="GALLERY" title="Our Journey in Pictures" text="Workshops, community engagement, educational events and professional recognition documented through supplied photographs."/><div className="mt-9 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{gallery.map((item,index)=><button key={item[0]} onClick={()=>setPhoto(index)} className="about-gallery-item"><img src={item[0]} alt={item[1]} loading="lazy"/><span>{item[1]}</span></button>)}</div></div></section>
    <section className="about-final-cta"><img src="/images/prism-official/prism-logo.jpg" alt=""/><div className="wrap"><h2>Let’s Build Your Educational Vision Together</h2><p>Every institution develops through thoughtful planning, responsible decisions, professional collaboration and continuous improvement.</p><div><Link to="/services" className="btn">Explore Our Services</Link><Link to="/contact?enquiry=consultation" className="cta-outline">Request Consultation</Link></div></div></section>
    <Lightbox item={photo===null?null:gallery[photo]} onClose={()=>setPhoto(null)} onMove={movePhoto}/>
  </div>
}
