import {useEffect,useState} from 'react';
import AwardsGallery from './AwardsGallery';
import {Link} from 'react-router-dom';
import './events-awards.css';
import {ArrowLeft,ArrowRight,Award,BookOpen,Building2,Bus,CheckCircle2,FlaskConical,Globe2,Handshake,Lightbulb,Maximize2,Megaphone,MonitorCog,Presentation,School,ShieldCheck,ShoppingBag,Trophy,Users,X} from 'lucide-react';

const participants=[
  [School,'School owners and management representatives'],[Users,'Principals, teachers and education professionals'],[Lightbulb,'Education consultants and subject experts'],[ShieldCheck,'Government, licensing and institutional stakeholders'],[ShoppingBag,'School-product and service vendors'],[MonitorCog,'Technology, digital, STEM and training partners'],[Building2,'Landowners and education-sector collaborators'],
];
const highlights=[
  [Award,'School and Principal Recognition','A professional space to acknowledge meaningful contributions to education.'],[Users,'Education Leadership Interaction','Opportunities for educators and institutional leaders to exchange perspectives.'],[Presentation,'Good-Practice Showcases','Practical ideas and approaches shared across the education community.'],[BookOpen,'Panel Discussions and Knowledge Sessions','Focused conversations around contemporary institutional needs.'],[Handshake,'School–Vendor Networking','Direct professional interaction between schools and solution providers.'],[MonitorCog,'Product and Service Demonstrations','A platform for relevant education solutions to be presented responsibly.'],[Globe2,'Collaboration Opportunities','Connections that may support future professional cooperation.'],[Trophy,'Professional Relationship Building','Meaningful networking across the wider education ecosystem.'],
];
const vendorAreas=[[Building2,'Furniture & classrooms'],[BookOpen,'Books, stationery & uniforms'],[FlaskConical,'Laboratory, STEM & robotics'],[MonitorCog,'Computers, smart classrooms & ERP'],[ShieldCheck,'CCTV, safety & transport'],[Bus,'Sports & playground equipment'],[Globe2,'Web, mobile & digital services'],[Megaphone,'Branding, admissions & marketing'],[Handshake,'Licensing, legal & professional services']];
const awardMedia=[
  {src:'/images/events-awards/education-conclave-recognition.jpg',alt:'Prism Education representative receiving a certificate at an education conclave',caption:'Professional recognition received at an education-sector conclave.'},
  {src:'/images/events-awards/eldrok-award-recognition.jpg',alt:'Prism Education representative holding an award at the Eldrok education event',caption:'Education-sector recognition at an Eldrok event.'},
  {src:'/images/events-awards/india-k12-awards-2025.jpg',alt:'Prism Education representative receiving recognition at the India K-12 Awards',caption:'India K-12 Awards — 8 October 2025, Hyatt, Kalyani.'},
];
const participationTypes=['Principal','School Owner/Management Representative','School Leadership Team Member','Teacher/Educator','Vendor/Service Provider','Speaker/Expert','Award Nomination','Other Education Stakeholder'];

function SectionHeading({eyebrow,title,text}){return <div className="mx-auto max-w-4xl text-center"><p className="section-kicker">{eyebrow}</p><h2 className="section-heading">{title}</h2>{text&&<p className="mx-auto mt-5 max-w-3xl leading-8 text-slate-600">{text}</p>}</div>}

function InterestForm(){const[status,setStatus]=useState('idle');const submit=e=>{e.preventDefault();if(!e.currentTarget.reportValidity())return;setStatus('ready')};return <div className="events-form-card" id="event-registration"><SectionHeading eyebrow="EXPRESSION OF INTEREST" title="Register Your Interest" text="If you are interested in attending, participating, receiving recognition, exhibiting your services or connecting with education stakeholders, please share your details with us."/>{status==='ready'?<div className="mt-8 rounded-2xl border border-amber-200 bg-amber-50 p-6 text-center" role="status"><CheckCircle2 className="mx-auto text-amber-600" size={38}/><h3 className="mt-3 text-xl">Continue through Prism Education’s enquiry channel</h3><p className="mt-2 text-sm leading-6">A dedicated event-registration backend is not configured yet, so no submission has been claimed or stored.</p><Link className="btn mt-5" to="/contact?enquiry=events-awards">Continue to Contact Form</Link><button className="ml-3 mt-5 text-sm font-bold text-[#10263f]" onClick={()=>setStatus('idle')}>Edit details</button></div>:<form className="mt-9" onSubmit={submit}><div className="grid gap-4 md:grid-cols-2"><label>Full Name<input className="field mt-2" name="name" autoComplete="name" required/></label><label>School/Organisation Name<input className="field mt-2" name="organization" required/></label><label>Designation<input className="field mt-2" name="designation" required/></label><label>Mobile Number<input className="field mt-2" name="phone" type="tel" inputMode="tel" autoComplete="tel" pattern="[0-9+() -]{7,18}" required/></label><label>Email Address<input className="field mt-2" name="email" type="email" autoComplete="email" required/></label><label>City<input className="field mt-2" name="city" autoComplete="address-level2" required/></label><label>Participation Type<select className="field mt-2" name="participationType" required defaultValue=""><option value="" disabled>Select participation type</option>{participationTypes.map(item=><option key={item}>{item}</option>)}</select></label><label>Area of Interest<input className="field mt-2" name="interest" required/></label><label className="md:col-span-2">Short Message<textarea className="field mt-2" name="message" rows="4" required/></label></div><label className="mt-4 flex items-start gap-2 text-xs font-medium"><input className="mt-1" type="checkbox" required/>I consent to being contacted by Prism Education regarding this expression of interest.</label><button className="btn mt-6" type="submit">Register My Interest <ArrowRight size={16}/></button></form>}</div>}

function MediaGallery(){return <AwardsGallery existingMedia={awardMedia}/>}

export default function EventsAwardsPage(){useEffect(()=>{const previousTitle=document.title;const description='Prism Edu Consultancy presents the Principals and School Leadership Award, celebrating excellence and connecting education stakeholders.';document.title='Principals and School Leadership Award | Prism Edu Consultancy';const selectors=['meta[name="description"]','meta[property="og:title"]','meta[property="og:description"]'];const previous=selectors.map(selector=>{const element=document.querySelector(selector);return element?{element,content:element.getAttribute('content')}:{element:null,content:null}});const values=[description,'Principals and School Leadership Award | Prism Edu Consultancy',description];previous.forEach((item,index)=>item.element?.setAttribute('content',values[index]));return()=>{document.title=previousTitle;previous.forEach(item=>item.element&&item.element.setAttribute('content',item.content||''))}},[]);return <div className="events-awards-page">
  <section className="events-awards-hero"><div className="wrap events-hero-grid"><div><p className="section-kicker">PRISM EDU CONSULTANCY PRESENTS</p><h1>Principals and School Leadership Award</h1><p className="events-tagline">Celebrating Excellence <span>•</span> Connecting Education</p><p className="mt-5 max-w-2xl leading-8 events-hero-description">A professional platform created to honour the valuable contributions of principals, school leadership teams, teachers and educational institutions while connecting stakeholders working for the progress of education.</p><div className="mt-6 flex flex-wrap gap-3">{[[Award,'Showcase Good Practices'],[Users,'Meet Education Leaders'],[Handshake,'Build Meaningful Networks']].map(([Icon,text])=><span className="event-point" key={text}><Icon size={17}/>{text}</span>)}</div><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a className="btn" href="#event-registration">Register Your Interest</a><a className="cta-outline" href="#awards-recognition">Explore Awards</a></div></div><figure className="events-hero-visual"><img src="/images/events-awards/principals-school-leadership-award.jpg" alt="Prism Edu Consultancy Principals and School Leadership Award" width="1121" height="1403" fetchPriority="high" loading="eager"/><figcaption>Principals and School Leadership Award — celebrating excellence and connecting education.</figcaption></figure></div></section>
  <section className="events-network py-16 md:py-24"><div className="wrap"><SectionHeading eyebrow="ABOUT THE EVENT" title="Connecting the Education Ecosystem" text="The proposed event creates an opportunity for knowledge-sharing, professional interaction, collaboration, recognition and practical school-development support. Participation by any organisation or authority is not implied until confirmed."/><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{participants.map(([Icon,text])=><article className="event-network-card" key={text}><Icon size={23}/><h3>{text}</h3></article>)}</div></div></section>
  <section className="events-highlights py-16 md:py-24"><div className="wrap"><SectionHeading eyebrow="EVENT HIGHLIGHTS" title="What to Expect"/><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{highlights.map(([Icon,title,text])=><article className="event-highlight-card" key={title}><Icon size={24}/><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
  <section className="event-vendor-section py-16 md:py-24"><div className="wrap"><SectionHeading eyebrow="SCHOOL–VENDOR NETWORKING" title="Connecting Schools with Trusted Solution Providers" text="A professional networking and requirement-sharing opportunity for schools and service providers. Participation does not represent a guarantee of vendor quality or business outcomes."/><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{vendorAreas.map(([Icon,text])=><div className="vendor-area" key={text}><Icon size={20}/><span>{text}</span></div>)}</div><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><a className="btn" href="#event-registration">Register as a School</a><a className="cta-outline" href="#event-registration">Register as a Vendor</a></div></div></section>
  <section className="events-information py-16 md:py-24"><div className="wrap grid gap-8 lg:grid-cols-[.9fr_1.1fr]"><div><p className="section-kicker">EVENT INFORMATION</p><h2 className="section-heading">Principals and School Leadership Award</h2><p className="mt-5 leading-7 text-slate-600">Event date and venue details will be announced in the coming days.</p></div><dl className="event-info-panel">{[['Event','Principals and School Leadership Award'],['Organised by','Prism Edu Consultancy'],['Participants','Principals, school leadership teams, educators, schools, vendors and education stakeholders'],['Date','To Be Announced'],['Venue','To Be Announced'],['Registration','Expression of Interest Open']].map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl></div></section>
  <section className="events-registration py-16 md:py-24"><div className="wrap"><InterestForm/></div></section>
  <section id="awards-recognition" className="awards-recognition py-16 md:py-24"><div className="wrap"><SectionHeading eyebrow="PROFESSIONAL CONTRIBUTIONS & EXCELLENCE" title="Awards & Recognition" text="Only approved photographs and neutral, verifiable captions are presented."/><MediaGallery/><p className="mt-7 text-center text-xs text-slate-500">Recognition details are presented from available records and approved supporting material.</p></div></section>
  <section className="recognition-video py-16 md:py-24"><div className="wrap"><SectionHeading eyebrow="EVENT MEDIA" title="Recognition Moments" text="A dedicated event video will appear here once the approved video file is available in the project."/><div className="video-placeholder" role="img" aria-label="Event video awaiting approved media"><Award size={52}/><p>Approved event video to be added</p><small>No unavailable or unverified media is presented.</small></div></div></section>
  <section className="why-event-platform py-16 md:py-20"><div className="wrap grid items-center gap-8 md:grid-cols-[180px_1fr]"><img src="/images/events-awards/prism-event-logo.jpg" alt="Prism Edu Consultancy logo" width="180" height="180" loading="lazy"/><div><p className="section-kicker">WHY PRISM CREATES THIS PLATFORM</p><h2 className="section-heading">Stronger connections for stronger schools</h2><p className="mt-5 max-w-3xl leading-8 text-slate-600">Prism Edu Consultancy aims to connect education stakeholders, understand institutional requirements, support professional collaboration and encourage the sharing of practical ideas for stronger schools.</p></div></div></section>
  <section className="events-final-cta"><div className="wrap text-center"><h2>Be Part of the Education Network</h2><p>Join schools, principals, educators, service providers and other stakeholders in a platform designed for recognition, interaction and meaningful collaboration.</p><div><a className="btn" href="#event-registration">Register Your Interest</a><Link className="cta-outline" to="/contact">Contact Prism Education</Link><Link className="cta-outline" to="/contact?enquiry=consultation">Request Consultation</Link></div></div></section>
</div>}
