import './home-hero.css';
import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {ArrowRight,Award,BriefcaseBusiness,Building2,CalendarCheck,ChartNoAxesCombined,ChevronLeft,ChevronRight,ClipboardCheck,Globe2,GraduationCap,Handshake,LandPlot,Lightbulb,MapPin,MessageCircleQuestion,MonitorCog,School,Search,Settings,ShoppingBag,Target,TrendingUp,Users} from 'lucide-react';

const slides=[
  {label:'PREMIUM SCHOOL BUSINESS MEETING',title:'Bring your school idea, challenge or opportunity to the table.',text:'A focused conversation to understand your context and identify practical next steps.',points:['New school','Existing school','Property','Growth'],primary:['Book a Meeting','/business-meeting'],secondary:['Explore Services','/services'],image:'/images/hero-slides/hero-upload-3.jpg',position:'78% center',mobilePosition:'70% center'},
  {label:'SCHOOL SERVICES',title:'Plan, establish, improve and manage your school with clarity.',text:'Connected support across feasibility, academics, operations, admissions and leadership.',points:['Feasibility','Setup','Academics','Operations'],primary:['Explore Our Services','/services#school-services'],secondary:['Request Consultation','/contact'],image:'/images/prism-official/school-workshop.jpg',position:'center',mobilePosition:'58% center'},
  {label:'SCHOOL LAND MARKETPLACE',title:'Find property suited to education projects—or list what you have.',text:'Search available and required land, buildings, rent, sale and lease opportunities.',points:['Available','Required','Rent','Lease'],primary:['Explore School Land','/school-land'],secondary:['List Property','/school-land/list'],image:'/images/prism-official/school-land-location-background.png',position:'center',mobilePosition:'64% center'},
  {label:'SCHOOL e-MARKETPLACE',title:'Connect school requirements with materials, equipment and services.',text:'Explore listings, post requirements, list items or begin a school procurement enquiry.',points:['Buy','Sell','Rent','Share'],primary:['Explore Marketplace','/school-materials'],secondary:['List Material','/school-materials/list'],image:'/images/prism-official/school-material-marketplace-background.png',position:'center',mobilePosition:'66% center'},
  {label:'PRISM EDU HELPLINE',title:'Have a school-related question? Share it with Prism Edu.',text:'A clear starting point for promoters, owners, educators, parents, students and vendors.',points:['Schools','Educators','Parents','Students'],primary:['Ask Prism Edu','/resources#student-parent-helpline'],secondary:['Contact Us','/contact'],image:'/images/prism-official/school-community.jpg',position:'center',mobilePosition:'58% center'},
];

function Action({item,secondary=false}){return <Link to={item[1]} className={secondary?'inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-white/30 bg-[#10263f]/35 px-5 py-3 text-sm font-bold text-white transition hover:bg-white/20':'inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-[#eeb640] px-5 py-3 text-sm font-bold text-[#10263f] transition hover:-translate-y-0.5 hover:bg-[#f3c35d]'}>{item[0]}<ArrowRight size={17}/></Link>}

export function HeroRedesign(){
  const[index,setIndex]=useState(0),[paused,setPaused]=useState(false),[touch,setTouch]=useState(null),[pageHidden,setPageHidden]=useState(document.hidden);
  const move=n=>setIndex(i=>(i+n+slides.length)%slides.length);
  useEffect(()=>{const update=()=>setPageHidden(document.hidden);document.addEventListener('visibilitychange',update);return()=>document.removeEventListener('visibilitychange',update)},[]);
  useEffect(()=>{if(paused||pageHidden||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const id=setTimeout(()=>move(1),6000);return()=>clearTimeout(id)},[index,paused,pageHidden]);
  return <section className="prism-home-hero" aria-roledescription="carousel" aria-label="Prism Edu ecosystem" onMouseEnter={()=>setPaused(true)} onMouseLeave={()=>setPaused(false)} onFocusCapture={()=>setPaused(true)} onBlurCapture={e=>{if(!e.currentTarget.contains(e.relatedTarget))setPaused(false)}} onTouchStart={e=>setTouch(e.touches[0].clientX)} onTouchEnd={e=>{if(touch!==null){const d=e.changedTouches[0].clientX-touch;if(Math.abs(d)>45)move(d<0?1:-1)}setTouch(null)}}>
    <div className="prism-home-hero-stage">{slides.map((s,i)=><article key={s.label} aria-hidden={i!==index} inert={i!==index} className={'prism-home-hero-slide '+(i===index?'is-active':'')} style={{'--hero-position':s.position,'--hero-mobile-position':s.mobilePosition}}>
      <img className="prism-home-hero-media" src={s.image} alt={i===index?s.label+' — '+s.title:''} width="1600" height="900" loading="eager" decoding="async" fetchPriority={i===0?'high':'auto'}/>
      <div className="prism-home-hero-shade" aria-hidden="true"/>
      <div className="prism-home-hero-content"><p>{s.label}</p><h1>{s.title}</h1><div className="prism-home-hero-description">{s.text}</div><div className="prism-home-hero-points">{s.points.map(point=><span key={point}>{point}</span>)}</div><div className="prism-home-hero-actions"><Action item={s.primary}/><Action item={s.secondary} secondary/></div></div>
    </article>)}</div>
    <button type="button" onClick={()=>move(-1)} className="prism-home-hero-arrow is-previous" aria-label="Previous hero slide"><ChevronLeft/></button>
    <button type="button" onClick={()=>move(1)} className="prism-home-hero-arrow is-next" aria-label="Next hero slide"><ChevronRight/></button>
    <div className="prism-home-hero-dots" aria-label="Choose hero slide">{slides.map((s,i)=><button type="button" key={s.label} onClick={()=>setIndex(i)} className={i===index?'is-active':''} aria-label={'Show '+s.label} aria-current={i===index?'true':undefined}/>)}</div>
  </section>
}
const pillars=[
  [BriefcaseBusiness,'Meet','Premium School Business Meeting','/business-meeting'],
  [ClipboardCheck,'Plan','Our Services','/services'],
  [LandPlot,'Find','School Land Marketplace','/school-land'],
  [ShoppingBag,'Connect','School e-Marketplace','/school-materials'],
  [MessageCircleQuestion,'Get Support','Edu Helpline','/resources#student-parent-helpline'],
];
export function CorePillars(){return <section className="bg-[#f7f8fb] py-14 md:py-20"><div className="mx-auto max-w-[1320px] px-5 md:px-8"><div className="mx-auto mb-10 max-w-3xl text-center"><p className="text-xs font-extrabold tracking-[.2em] text-[#d99a16]">THE PRISM EDU ECOSYSTEM</p><h2 className="mt-3 text-[clamp(1.9rem,4vw,3.2rem)] font-extrabold tracking-tight text-[#10263f]">Five clear ways to move forward</h2></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{pillars.map(([Icon,kicker,title,to],i)=><Link to={to} key={title} className="group relative min-h-[190px] overflow-hidden rounded-2xl border border-slate-200 bg-white p-6 shadow-[0_12px_38px_rgba(16,38,63,.07)] transition duration-300 hover:-translate-y-1 hover:border-[#eeb640]/60 hover:shadow-xl"><span className="absolute right-4 top-3 text-5xl font-black text-slate-100">0{i+1}</span><span className="relative grid h-12 w-12 place-items-center rounded-xl bg-[#10263f] text-[#eeb640]"><Icon size={23}/></span><p className="relative mt-6 text-xs font-bold uppercase tracking-wider text-[#d99a16]">{kicker}</p><h3 className="relative mt-1 text-lg font-bold text-[#10263f]">{title}</h3><ArrowRight className="relative mt-4 transition group-hover:translate-x-1" size={18}/></Link>)}</div></div></section>}

export function AboutPrismPreview(){return <section className="overflow-hidden bg-white py-16 md:py-24"><div className="mx-auto grid max-w-[1240px] items-center gap-10 px-5 md:px-8 lg:grid-cols-[.9fr_1.1fr]"><div className="relative"><div className="absolute -left-5 -top-5 h-28 w-28 rounded-3xl bg-[#eeb640]/20"/><img src="/images/prism-official/founder-dr-prajkta-shinde.jpg" alt="Dr. Prajkta Shinde, Founder and Educational Consultant at Prism Edu" className="relative h-[430px] w-full rounded-[2rem] object-cover object-top shadow-2xl md:h-[520px]"/><div className="absolute -bottom-5 right-4 max-w-[250px] rounded-2xl bg-[#10263f] p-5 text-white shadow-xl"><p className="text-xs font-bold tracking-[.14em] text-[#f3c35d]">FOUNDER</p><p className="mt-2 text-lg font-bold">Dr. Prajkta Shinde</p><p className="mt-1 text-sm text-white/70">Founder & Educational Consultant</p></div></div><div><p className="text-xs font-extrabold tracking-[.2em] text-[#d99a16]">ABOUT PRISM EDU</p><h2 className="mt-3 text-3xl font-extrabold tracking-tight text-[#10263f] md:text-5xl">Building stronger educational institutions, together</h2><p className="mt-6 text-base leading-8 text-slate-600">Prism Edu Consultancy is an education advisory and support platform for K–12 schools, educational trusts, societies, school promoters and education entrepreneurs.</p><p className="mt-4 text-base leading-8 text-slate-600">From concept planning and feasibility to school setup, land, academics, administration, licensing, vendor solutions, branding and digital transformation, our support is practical, collaborative and requirement-driven.</p><div className="mt-7 flex flex-wrap gap-2">{['Planning','Academics','Compliance','Infrastructure','Technology','Growth'].map(x=><span key={x} className="rounded-full bg-[#eef3f8] px-4 py-2 text-sm font-semibold text-[#10263f]">{x}</span>)}</div><Link to="/about" className="mt-8 inline-flex min-h-12 items-center gap-2 rounded-xl bg-[#10263f] px-6 py-3 text-sm font-bold text-white">Know More About Prism Edu<ArrowRight size={17}/></Link></div></div></section>}

export function BusinessMeetingSection(){const topics=['Start a New School','Existing School Improvement','School Management','Admissions','Marketing','School Property','Vendor Requirements','Digital Services','Training & Workshops'];return <section className="relative overflow-hidden bg-white py-16 md:py-24"><div className="absolute -right-36 top-0 h-96 w-96 rounded-full bg-[#eeb640]/10 blur-3xl"/><div className="relative mx-auto grid max-w-[1320px] items-center gap-10 px-5 md:px-8 lg:grid-cols-[.9fr_1.1fr]"><div className="rounded-[2rem] bg-gradient-to-br from-[#10263f] to-[#49366f] p-7 text-white shadow-2xl md:p-10"><BriefcaseBusiness size={44} className="text-[#eeb640]"/><p className="mt-8 text-xs font-bold tracking-[.18em] text-[#f3c35d]">PRIMARY CONSULTATION SERVICE</p><h2 className="mt-3 text-3xl font-extrabold text-white md:text-4xl">Premium School Business Meeting</h2><p className="mt-4 leading-7 text-white/70">A focused discussion around your school project, requirement, challenge or opportunity.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Link className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-[#eeb640] px-5 py-3 text-sm font-bold text-[#10263f]" to="/business-meeting">Schedule a Business Meeting<ArrowRight size={16}/></Link><Link className="inline-flex min-h-12 items-center justify-center rounded-xl border border-white/25 px-5 py-3 text-sm font-bold" to="/contact">Send Enquiry</Link></div></div><div><p className="text-xs font-extrabold tracking-[.18em] text-[#d99a16]">A PRACTICAL STARTING POINT</p><h2 className="mt-3 text-3xl font-extrabold tracking-tight text-[#10263f] md:text-5xl">One conversation. A clearer direction.</h2><div className="mt-7 grid gap-3 sm:grid-cols-2">{topics.map(t=><div key={t} className="flex items-center gap-3 rounded-xl border border-slate-100 bg-[#f8f9fb] p-4 text-sm font-semibold text-[#10263f]"><span className="h-2 w-2 rounded-full bg-[#eeb640]"/>{t}</div>)}</div></div></div></section>}

const serviceGroups={
  'School Services':{icon:School,items:['Project Feasibility','New School Setup','School Incubation','School Improvement','School Management','Academic Planning','Admission Strategy','Licensing Guidance','Curriculum Improvement','School Audit']},
  'Support Services':{icon:Handshake,items:['School Land Search','School Property Listing','Existing School Sale Support','Existing School Lease Support','Vendor Identification','Procurement Support','Recruitment Support','Documentation Assistance','Marketplace Support','Business Consultation']},
  'Digital Services':{icon:MonitorCog,items:['School Website Development','Website Redesign','Mobile Application','School ERP','Digital Marketing','Social Media Marketing','SEO','Branding & Graphic Design','Lead Management','Online Admission Enquiry']},
};
export function ServiceTabs(){const[active,setActive]=useState('School Services'),data=serviceGroups[active],Icon=data.icon;return <section className="bg-[#eef3f8] py-16 md:py-24"><div className="mx-auto max-w-[1200px] px-5 md:px-8"><div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><p className="text-xs font-extrabold tracking-[.2em] text-[#d99a16]">OUR SERVICES</p><h2 className="mt-3 text-3xl font-extrabold text-[#10263f] md:text-5xl">Support organized around your needs</h2></div><div className="flex gap-2 overflow-x-auto pb-2" role="tablist">{Object.keys(serviceGroups).map(k=><button role="tab" aria-selected={active===k} onClick={()=>setActive(k)} key={k} className={'min-h-11 whitespace-nowrap rounded-full px-5 py-2.5 text-sm font-bold transition '+(active===k?'bg-[#10263f] text-white shadow-lg':'border border-slate-300 bg-white text-[#10263f] hover:border-[#eeb640]')}>{k}</button>)}</div></div><div className="mt-10 grid gap-7 rounded-[2rem] border border-white bg-white p-6 shadow-[0_22px_65px_rgba(16,38,63,.09)] md:grid-cols-[.35fr_.65fr] md:p-10"><div className="rounded-2xl bg-gradient-to-br from-[#10263f] to-[#334f70] p-7 text-white"><Icon size={48} className="text-[#eeb640]"/><h3 className="mt-6 text-2xl font-bold text-white">{active}</h3><p className="mt-3 text-sm leading-6 text-white/70">Focused guidance and implementation assistance aligned with your school context.</p><Link to="/services" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-[#f3c35d]">View complete services<ArrowRight size={16}/></Link></div><div className="grid gap-3 sm:grid-cols-2">{data.items.map(item=><div key={item} className="flex items-center gap-3 rounded-xl border border-slate-100 bg-[#f8f9fb] p-4 text-sm font-semibold text-[#10263f]"><Target size={17} className="shrink-0 text-[#d99a16]"/>{item}</div>)}</div></div></div></section>}

const workshops=[[GraduationCap,'Teacher Training'],[Users,'Leadership Training'],[Settings,'School Management Workshop'],[TrendingUp,'Admission Team Training'],[Handshake,'Parenting Workshop'],[Lightbulb,'Student Workshop'],[ClipboardCheck,'Administrative Staff Training']];
export function TrainingWorkshops(){return <section className="bg-white py-16 md:py-24"><div className="mx-auto max-w-[1320px] px-5 md:px-8"><div className="mb-10 max-w-3xl"><p className="text-xs font-extrabold tracking-[.2em] text-[#d99a16]">TRAINING & WORKSHOPS</p><h2 className="mt-3 text-3xl font-extrabold text-[#10263f] md:text-5xl">Practical development for school communities</h2></div><div className="flex snap-x gap-4 overflow-x-auto pb-5 lg:grid lg:grid-cols-4 lg:overflow-visible">{workshops.map(([Icon,title])=><article key={title} className="min-w-[250px] snap-start rounded-2xl border border-slate-200 p-6 transition hover:-translate-y-1 hover:border-[#eeb640]"><Icon className="text-[#d99a16]"/><h3 className="mt-5 text-lg font-bold text-[#10263f]">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">Structured learning support designed around the participating group and school context.</p></article>)}</div><Link to="/contact" className="mt-7 inline-flex min-h-12 items-center gap-2 rounded-xl bg-[#10263f] px-5 py-3 text-sm font-bold text-white">Request Workshop<ArrowRight size={16}/></Link></div></section>}

const process=[[Search,'Understand','Listen to the requirement.'],[ClipboardCheck,'Review','Study available information.'],[MessageCircleQuestion,'Discuss','Explore practical options.'],[MapPin,'Plan','Identify suitable next steps.'],[Handshake,'Support','Assist where engaged.']];
export function WorkProcess(){return <section className="bg-[#f7f8fb] py-16 md:py-24"><div className="mx-auto max-w-[1200px] px-5 md:px-8"><div className="mx-auto mb-12 max-w-3xl text-center"><p className="text-xs font-extrabold tracking-[.2em] text-[#d99a16]">HOW WE WORK</p><h2 className="mt-3 text-3xl font-extrabold text-[#10263f] md:text-5xl">A thoughtful path from requirement to support</h2></div><div className="grid gap-4 md:grid-cols-5">{process.map(([Icon,title,text],i)=><article key={title} className="relative rounded-2xl border border-slate-200 bg-white p-5 text-center shadow-sm"><span className="mx-auto grid h-12 w-12 place-items-center rounded-full bg-[#10263f] text-[#eeb640]"><Icon size={21}/></span><p className="mt-4 text-xs font-extrabold text-slate-400">0{i+1}</p><h3 className="mt-1 text-lg font-bold text-[#10263f]">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p>{i<4&&<ArrowRight className="absolute -right-4 top-1/2 z-10 hidden text-[#d99a16] md:block" size={18}/>}</article>)}</div></div></section>}

const journeyImages=[
  ['/images/prism-official/school-workshop.jpg','Prism Edu school workshop and professional learning session'],
  ['/images/prism-official/school-community.jpg','Prism Edu engaging with a school community'],
];
export function ProfessionalJourney(){return <section className="bg-white py-16 md:py-24"><div className="mx-auto max-w-[1240px] px-5 md:px-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-extrabold tracking-[.2em] text-[#d99a16]">PROFESSIONAL JOURNEY</p><h2 className="mt-3 text-3xl font-extrabold text-[#10263f] md:text-5xl">Education in practice</h2><p className="mt-4 max-w-2xl leading-7 text-slate-600">Moments from school visits, workshops, professional events and educational engagement.</p></div><Link to="/about" className="inline-flex items-center gap-2 text-sm font-bold text-[#10263f]">Explore About Prism Edu<ArrowRight size={16}/></Link></div><div className="mt-9 grid gap-5 md:grid-cols-2">{journeyImages.map(([src,alt],i)=><figure key={src} className="group overflow-hidden rounded-[1.75rem] bg-[#10263f]"><img src={src} alt={alt} className="h-72 w-full object-cover transition duration-500 group-hover:scale-[1.025] md:h-96"/><figcaption className="px-6 py-5 text-sm font-semibold text-white">{i===0?'Workshops & professional learning':'School community engagement'}</figcaption></figure>)}</div></div></section>}

export function VerifiedRecognition(){return <section className="bg-[#eef3f8] py-16 md:py-24"><div className="mx-auto grid max-w-[1240px] gap-9 px-5 md:px-8 lg:grid-cols-[.75fr_1.25fr]"><div><span className="grid h-14 w-14 place-items-center rounded-2xl bg-[#10263f] text-[#eeb640]"><Award size={27}/></span><p className="mt-7 text-xs font-extrabold tracking-[.2em] text-[#d99a16]">AWARDS & ACHIEVEMENTS</p><h2 className="mt-3 text-3xl font-extrabold text-[#10263f] md:text-5xl">Recognising professional contribution</h2><p className="mt-5 leading-7 text-slate-600">Published here only where photographic documentation has been supplied. Additional award names and details can be added after approval and verification.</p></div><div className="grid gap-5 sm:grid-cols-2"><figure className="overflow-hidden rounded-[1.75rem] bg-white shadow-lg"><img src="/images/prism-official/india-k12-award.jpg" alt="Dr. Prajkta Shinde receiving recognition at the India K-12 Awards event" className="h-72 w-full object-cover object-top"/><figcaption className="p-5"><p className="font-bold text-[#10263f]">India K-12 Awards event</p><p className="mt-1 text-sm text-slate-500">Professional recognition photograph supplied by Prism Edu.</p></figcaption></figure><figure className="overflow-hidden rounded-[1.75rem] bg-white shadow-lg"><img src="/images/prism-official/education-leadership-award.jpg" alt="Dr. Prajkta Shinde at an education leadership felicitation and award ceremony" className="h-72 w-full object-cover object-top"/><figcaption className="p-5"><p className="font-bold text-[#10263f]">Education leadership recognition</p><p className="mt-1 text-sm text-slate-500">Felicitation and award ceremony photograph supplied by Prism Edu.</p></figcaption></figure></div></div></section>}

export function EduHelpline(){return <section className="relative overflow-hidden bg-gradient-to-r from-[#10263f] to-[#49366f] py-16 text-white md:py-20"><div className="absolute -right-20 -top-24 h-72 w-72 rounded-full border-[40px] border-white/[.03]"/><div className="relative mx-auto flex max-w-[1200px] flex-col justify-between gap-8 px-5 md:px-8 lg:flex-row lg:items-center"><div className="flex gap-5"><span className="grid h-14 w-14 shrink-0 place-items-center rounded-2xl bg-white/10 text-[#eeb640]"><MessageCircleQuestion size={28}/></span><div><p className="text-xs font-bold tracking-[.18em] text-[#f3c35d]">PRISM EDU HELPLINE</p><h2 className="mt-2 text-3xl font-extrabold text-white">Have a school-related question?</h2><p className="mt-3 max-w-2xl leading-7 text-white/70">Share your context with Prism Edu. We’ll provide a clear starting point where the appropriate support channel is available.</p></div></div><Link to="/resources#student-parent-helpline" className="inline-flex min-h-12 shrink-0 items-center justify-center gap-2 rounded-xl bg-[#eeb640] px-6 py-3 text-sm font-bold text-[#10263f]">Ask Prism Edu<ArrowRight size={16}/></Link></div></section>}

export function FinalMeetingCTA(){return <section className="bg-[#eeb640] py-14"><div className="mx-auto flex max-w-[1200px] flex-col justify-between gap-6 px-5 md:px-8 lg:flex-row lg:items-center"><div><p className="text-xs font-extrabold tracking-[.18em] text-[#10263f]/60">A CLEAR FIRST STEP</p><h2 className="mt-2 text-3xl font-extrabold text-[#10263f] md:text-4xl">Start with a Premium School Business Meeting</h2><p className="mt-2 text-[#10263f]/70">Share your requirement and explore practical options without promises of predetermined outcomes.</p></div><Link to="/business-meeting" className="inline-flex min-h-12 shrink-0 items-center justify-center gap-2 rounded-xl bg-[#10263f] px-6 py-3 text-sm font-bold text-white">Book Business Meeting<ArrowRight size={17}/></Link></div></section>}

export function PremiumMeetingPage(){const topics=['Start a New School','Existing School Improvement','School Management','Admissions','Marketing','School Property','School Land','School Sale / Lease','Vendor Requirements','Digital Services','Training','Workshops'];return <><section className="bg-gradient-to-br from-[#10263f] to-[#49366f] py-16 text-white md:py-24"><div className="mx-auto max-w-[1100px] px-5 md:px-8"><p className="text-xs font-bold tracking-[.2em] text-[#f3c35d]">PREMIUM SCHOOL BUSINESS MEETING</p><h1 className="mt-4 max-w-4xl text-[clamp(2.2rem,6vw,4.7rem)] font-extrabold leading-[1.06] text-white">A focused discussion around your school project.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-white/70">Bring a requirement, challenge or opportunity. The meeting helps clarify context and identify suitable next steps.</p><Link to="/contact" className="mt-8 inline-flex min-h-12 items-center gap-2 rounded-xl bg-[#eeb640] px-6 py-3 text-sm font-bold text-[#10263f]">Schedule a Business Meeting<ArrowRight size={17}/></Link></div></section><section className="bg-white py-16 md:py-24"><div className="mx-auto max-w-[1100px] px-5 md:px-8"><h2 className="text-3xl font-extrabold text-[#10263f] md:text-4xl">Topics we can discuss</h2><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{topics.map(t=><div key={t} className="rounded-xl border border-slate-200 bg-[#f8f9fb] p-4 font-semibold text-[#10263f]">{t}</div>)}</div></div></section><section className="bg-[#eef3f8] py-16 md:py-20"><div className="mx-auto max-w-[1100px] px-5 md:px-8"><h2 className="text-3xl font-extrabold text-[#10263f]">Meeting process</h2><div className="mt-8 grid gap-4 md:grid-cols-4">{[['Share','Tell us your requirement.'],['Meet','Schedule a discussion.'],['Explore','Understand possible options.'],['Plan','Identify suitable next steps.']].map(([t,d],i)=><article key={t} className="rounded-2xl bg-white p-6 shadow-sm"><p className="text-sm font-extrabold text-[#d99a16]">0{i+1}</p><h3 className="mt-2 text-xl font-bold text-[#10263f]">{t}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{d}</p></article>)}</div></div></section></>}
