import {useEffect,useRef,useState} from 'react';
import {Link,useLocation} from 'react-router-dom';
import {ArrowRight,BadgeCheck,BookOpen,Building2,ChevronLeft,ChevronRight,ClipboardCheck,FileCheck2,Globe2,GraduationCap,Handshake,LandPlot,Lightbulb,Megaphone,MonitorCog,School,Settings,ShieldCheck,ShoppingBag,Target,TrendingUp,Users,X} from 'lucide-react';

export const serviceGroups=[
  {id:'school-services',number:'01',short:'School Services',title:'School Services',intro:'Support for planning, establishing, strengthening and growing educational institutions.',icon:School,tone:'bg-blue-50',link:'/contact?service=school-services',items:['School Feasibility Study and Planning','New School Setup','Preschool Setup','School Incubation','School Improvement and Restructuring','School Quality Assessment and Audit','School Management Support','Curriculum and Academic Development','School Admissions Strategy','Staff Recruitment and Placement','Teacher Training Programmes','Principal and Leadership Development','Effective Classroom Management','Administrative Staff Training','Admission Team Training','Parent Orientation Workshops','Student Development Workshops','Motivation and Awareness Programmes','Skill Development Programmes','IIT-JEE, NEET and Foundation Programme Coordination'],ctas:[['Book Business Meeting','/business-meeting'],['Discuss Your School Requirement','/contact?service=school-services']]},
  {id:'school-land-support',number:'02',short:'School Land & Support',title:'School Land & Support Services',intro:'Property discovery, listing and planning support for education-focused projects.',icon:LandPlot,tone:'bg-emerald-50',link:'/school-land',items:['School Resale','School Restructure','School Land Search','Land Available for School','School Building Search','Property Listing for Education Use','Land Requirement Submission','Site Visit and Preliminary Assessment','School Feasibility Support','Rent, Sale and Lease Coordination','School Architecture Coordination','Campus Infrastructure Planning','Location and Accessibility Review','Existing School Property Support'],ctas:[['Explore School Land Marketplace','/school-land'],['List Your Property','/school-land/list'],['Submit Land Requirement','/school-land/requirement']]},
  {id:'vendor-services',number:'03',short:'Industry Associates',title:'Industry Associates',intro:'Connect schools with products, equipment, professional vendors and material opportunities.',icon:ShoppingBag,tone:'bg-amber-50',link:'/school-materials',items:['School Furniture','Laboratory Equipment','Smart Classroom Solutions','Computers and IT Equipment','School ERP Solutions','School Transport','Books and Stationery','Uniforms and Accessories','Sports and Activity Equipment','CCTV, Safety and Security Systems','Educational Toys and Preschool Materials','Printing and Branding Materials','Material Available for Sale','Material Available for Rent or Lease','Used and Resale School Materials','Urgent Material Requirements','Vendor Registration and Listing','Vendor Discovery and Enquiry Support'],ctas:[['Explore School e-Marketplace','/school-materials'],['List School Materials','/school-materials/list'],['Submit Material Requirement','/school-materials/order'],['Register as a Vendor','/contact?service=vendor-registration']]},
  {id:'licensing-legal',number:'04',short:'Licensing & Legal',title:'Licensing & Legal Services',intro:'Professional coordination and documentation support for school registration, affiliation, permissions, and compliance processes.',icon:FileCheck2,tone:'bg-violet-50',link:'/licensing-affiliation',items:['Trust and Society Documentation Support','School Registration Guidance','Education NOC Coordination','Board Affiliation Support','CBSE Affiliation Coordination','State Board Documentation Support','Recognition and Permission Support','Fire, Safety and Health NOC Coordination','Building and Infrastructure Documentation','Compliance Documentation Support','Application Review and Follow-Up','Renewal and Ongoing Compliance Support','Government Department Liaison','Audit Documentation Support','Policy Documentation Coordination','Legal Professional Coordination'],ctas:[['Request Licensing Consultation','/contact?service=licensing'],['Discuss Your Requirements','/contact?service=documentation']]},
  {id:'digital-services',number:'05',short:'Web & Digital',title:'Web and Digital Solution Services',intro:'Practical, affordable and quality-driven digital solutions that help schools, educational institutions and startups improve their technology, communication, branding and online presence.',icon:Globe2,tone:'bg-cyan-50',link:'/services/website-quotation',items:['Website Development','Mobile Application Development','School ERP Solutions','Social Media Management','Digital Marketing & Advertising','Branding & Graphic Design','SEO & Online Visibility','Email & WhatsApp Solutions','Automation & Digital Integration'],ctas:[['Get Website Quotation','/services/website-quotation'],['Request Digital Consultation','/contact?service=digital'],['Chat on WhatsApp','/contact']]},
];

const navItems={
  'School Services':['School Feasibility Study','New School Setup','Preschool Setup','School Incubation','School Improvement','School Management Support','Academic Audit','Curriculum Development','Admissions Growth','Teacher Training'],
  'School Land & Support':['School Resale','School Restructure','School Land Search','Land Available for School','School Building Search','Property Listing','Site Assessment','Rent, Sale and Lease Support','Infrastructure Planning','Land Requirement Submission'],
  'Industry Associates':['School Furniture','Laboratory Equipment','Smart Classroom Solutions','Computers and IT','School ERP','School Transport','Books and Stationery','Used Material Marketplace','Vendor Registration'],
  'Licensing & Legal':['Trust/Society Documentation','Registration Guidance','Education NOC Coordination','Board Affiliation Support','CBSE Assistance','Compliance Guidance','Renewal Support','Government Coordination'],
  'Web & Digital':['School Website Development','Mobile Applications','School ERP','Admission Systems','Workflow Automation','Digital Marketing','Social Media','SEO Services','Branding and Design','Website Maintenance'],
};

const icons=[Target,Building2,Lightbulb,School,Settings,Users,ClipboardCheck,BadgeCheck,BookOpen,TrendingUp,Handshake,GraduationCap,Megaphone,ShieldCheck,MonitorCog,Globe2];
const slug=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');

function MegaMenu({open,onClose}){const heads=Object.keys(navItems);return <div className={'services-mega-menu '+(open?'is-open':'')} onMouseEnter={()=>{}} onMouseLeave={onClose} role="region" aria-label="Our Services mega menu"><div className="grid grid-cols-5 gap-6">{heads.map((head,i)=>{const group=serviceGroups[i],Icon=group.icon;return <div key={head}><Link to={'/services#'+group.id} onClick={onClose} className="mega-heading"><Icon size={20}/>{head}</Link><div className="mt-4 space-y-1.5">{navItems[head].map(item=><Link key={item} to={'/services#'+group.id+'-'+slug(item)} onClick={onClose} className="mega-link">{item}</Link>)}</div></div>})}</div></div>}

function ServicesHero(){return <section className="relative isolate overflow-hidden bg-[#10263f] py-20 text-white md:py-28"><img src="/images/prism-hero.png" alt="" className="absolute inset-0 -z-20 h-full w-full object-cover opacity-30"/><div className="absolute inset-0 -z-10 bg-gradient-to-r from-[#10263f] via-[#10263f]/95 to-[#146b73]/70"/><div className="wrap"><p className="section-kicker !text-[#f3c35d]">PRISM EDU CONSULTANCY SERVICES</p><h1 className="mt-4 max-w-4xl text-[clamp(2.3rem,6vw,5.1rem)] font-extrabold leading-[1.04] tracking-[-.04em] text-white">Practical Services for Stronger Educational Institutions</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-white/75">From school planning, land and licensing to materials, technology and growth, Prism Education brings essential support services together on one platform.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to="/contact" className="btn">Request Consultation<ArrowRight size={16}/></Link><a href="#school-services" className="cta-outline">Explore Our Services</a></div></div></section>}

function ServiceSection({group,index}){const Icon=group.icon;return <section id={group.id} className={'service-full-section scroll-mt-44 py-16 md:py-24 '+group.tone}><div className="mx-auto max-w-[1240px] px-5 md:px-8"><div className="grid gap-7 lg:grid-cols-[.35fr_.65fr]"><div className="lg:sticky lg:top-44 lg:self-start"><p className="text-6xl font-black text-[#10263f]/10">{group.number}</p><span className="mt-4 grid h-14 w-14 place-items-center rounded-2xl bg-[#10263f] text-[#eeb640]"><Icon size={28}/></span><h2 className="mt-6 text-[clamp(2rem,4vw,3.3rem)] font-extrabold leading-tight text-[#10263f]">{group.title}</h2><p className="mt-4 leading-7 text-slate-600">{group.intro}</p><div className="mt-7 flex flex-col gap-3">{group.ctas.map(([label,to],i)=><Link key={label} to={to} className={i===0?'btn':'btn2'}>{label}<ArrowRight size={15}/></Link>)}</div></div><div className="grid gap-4 sm:grid-cols-2">{group.items.map((item,i)=>{const ItemIcon=icons[i%icons.length];return <Link id={group.id+'-'+slug(item)} key={item} to={group.link} className="service-detail-card group"><ItemIcon size={21}/><div><h3>{item}</h3><p>{descriptionFor(item)}</p><span>Get assistance <ArrowRight size={14}/></span></div></Link>})}</div></div>{group.id==='licensing-legal'&&<p className="service-disclaimer">Licences, registrations and affiliations remain subject to the rules and approval of the relevant authorities. Prism Education provides guidance, documentation support and coordination.</p>}</div></section>}

function descriptionFor(item){if(/Land|Property|Site|Location|Infrastructure|Architecture/.test(item))return'Practical discovery, review or coordination support for education-use requirements.';if(/Website|Digital|SEO|Social|App|ERP|Automation|System|Analytics/.test(item))return'Technology and communication support aligned with institutional needs.';if(/Training|Workshop|Development|Curriculum|Academic|Classroom/.test(item))return'Focused academic and people-development support for school communities.';if(/Registration|Affiliation|NOC|Compliance|Documentation|Legal|Government|Renewal/.test(item))return'Guidance and coordination for relevant documentation and processes.';return'Professional support tailored to the school or education project context.'}

export function ServicesExperience(){const{hash}=useLocation(),[active,setActive]=useState(hash.slice(1).split('-').slice(0,2).join('-')||serviceGroups[0].id),[mega,setMega]=useState(false);useEffect(()=>{const link=[...document.querySelectorAll('header a')].find(a=>a.textContent.trim()==='Our Services');if(!link)return;const show=()=>setMega(true),hide=e=>{if(!e.relatedTarget?.closest?.('.services-mega-menu'))setMega(false)},key=e=>{if(e.key==='Escape')setMega(false)};link.setAttribute('aria-haspopup','true');link.addEventListener('mouseenter',show);link.addEventListener('focus',show);link.addEventListener('mouseleave',hide);addEventListener('keydown',key);return()=>{link.removeEventListener('mouseenter',show);link.removeEventListener('focus',show);link.removeEventListener('mouseleave',hide);removeEventListener('keydown',key)}},[]);useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(e=>e.isIntersecting&&setActive(e.target.id)),{rootMargin:'-38% 0px -52%'});serviceGroups.forEach(x=>{const el=document.getElementById(x.id);if(el)observer.observe(el)});return()=>observer.disconnect()},[]);return <><MegaMenu open={mega} onClose={()=>setMega(false)}/><ServicesHero/><nav className="service-sticky-nav" aria-label="Service categories"><div className="mx-auto flex max-w-[1240px] gap-2 overflow-x-auto px-4 py-3 md:px-8">{serviceGroups.map(x=>{const Icon=x.icon;return <a key={x.id} href={'#'+x.id} className={'service-sticky-link '+(active===x.id?'is-active':'')}><Icon size={17}/>{x.short}</a>})}</div></nav>{serviceGroups.map((x,i)=><ServiceSection key={x.id} group={x} index={i}/>)}</>}

export function ServicesExperienceClosing(){return <><section className="bg-white py-16 md:py-20"><div className="wrap grid gap-5 lg:grid-cols-2"><article className="marketplace-route-card"><LandPlot/><h2>Looking for School Land?</h2><p>Explore existing land listings, property requirements and education-use opportunities.</p><Link to="/school-land" className="btn">Explore School Land Marketplace</Link></article><article className="marketplace-route-card"><ShoppingBag/><h2>Looking for School Materials or Vendors?</h2><p>Browse school products, equipment, material listings and vendor opportunities.</p><Link to="/school-materials" className="btn">Explore Material Marketplace</Link></article></div></section><section className="relative overflow-hidden bg-gradient-to-br from-[#10263f] to-[#146b73] py-16 text-white md:py-20"><img src="/images/prism-official/prism-logo.jpg" alt="Prism Edu Consultancy" className="mx-auto mb-6 block h-[88px] w-[88px] rounded-xl object-contain md:h-28 md:w-28"/><div className="wrap relative text-center"><h2 className="text-[clamp(2rem,5vw,3.8rem)] font-extrabold text-white">Not sure which service your institution needs?</h2><p className="mx-auto mt-5 max-w-3xl leading-8 text-white/70">Share your requirement with Prism Education, and our team will help you identify a practical starting point.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Link to="/contact" className="btn">Request Consultation</Link><Link to="/contact" className="cta-outline">Contact Prism Education</Link><Link to="/" className="cta-outline">Return to Home</Link></div></div></section></>}
