import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {ArrowRight,BookOpen,Building2,ClipboardCheck,FileCheck2,Globe2,GraduationCap,LandPlot,MonitorCog,School,ShoppingBag,Target,Users} from 'lucide-react';
import {serviceGroups,ServicesExperienceClosing} from './ServicesExperience';

const sectionImages={
  'school-services':['/images/prism-official/school-workshop.jpg','School leadership, teacher development and institutional training'],
  'school-land-support':['/images/hero-slides/hero-upload-1.jpg','School campus and education property planning'],
  'vendor-services':['/images/hero-slides/hero-upload-2.jpg','School materials, equipment and vendor solutions'],
  'licensing-legal':['/images/hero-slides/hero-upload-3.jpg','School documentation, compliance and affiliation guidance'],
  'digital-services':['/images/prism-hero.png','Digital systems and technology solutions for educational institutions'],
};
const itemIcons=[Target,Building2,BookOpen,Users,ClipboardCheck,GraduationCap,FileCheck2,MonitorCog];

function itemDescription(item){if(/land|property|site|campus|location|architecture/i.test(item))return'Practical discovery, review and coordination support for education-use requirements.';if(/website|digital|seo|social|application|erp|automation|system|analytics/i.test(item))return'Technology and communication support aligned with institutional requirements.';if(/training|workshop|academic|curriculum|classroom|student|teacher|principal/i.test(item))return'Focused academic and professional-development support for school communities.';if(/registration|affiliation|noc|compliance|documentation|legal|government|renewal/i.test(item))return'Guidance and coordination for relevant documentation and regulatory processes.';return'Professional assistance shaped around the institution and its current stage.'}

function ServiceSection({group,index}){const Icon=group.icon,[image,alt]=sectionImages[group.id],reverse=index%2===1;return <section id={group.id} className={'service-visual-section scroll-mt-[154px] py-16 md:py-24 '+group.tone}><div className="mx-auto max-w-[1380px] px-5 md:px-8"><div className="grid items-start gap-9 lg:grid-cols-[1.15fr_.85fr] xl:gap-14"><div className={reverse?'lg:order-2':''}><div className="flex items-start gap-5"><span className="grid h-14 w-14 shrink-0 place-items-center rounded-2xl bg-[#10263f] text-[#eeb640]"><Icon size={28}/></span><div><p className="text-sm font-black tracking-[.18em] text-[#10263f]/35">{group.number}</p><h2 className="mt-1 text-[clamp(2rem,4vw,3.35rem)] font-extrabold leading-tight text-[#10263f]">{group.title}</h2></div></div><p className="mt-5 max-w-3xl text-base leading-8 text-slate-600">{group.intro}</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{group.items.map((item,i)=>{const ItemIcon=itemIcons[i%itemIcons.length];return <Link key={item} to={group.link} className="service-compact-card group"><ItemIcon size={19}/><div><h3>{item}</h3><p>{itemDescription(item)}</p><span>Get assistance <ArrowRight size={13}/></span></div></Link>})}</div><div className="mt-8 flex flex-col gap-3 sm:flex-row sm:flex-wrap">{group.ctas.map(([label,to],i)=><Link key={label} to={to} className={i===0?'btn':'btn2'}>{label}<ArrowRight size={15}/></Link>)}</div></div><figure className={'service-visual-figure '+(reverse?'lg:order-1':'')}><img src={image} alt={alt} width="720" height="900" loading={index===0?'eager':'lazy'}/><figcaption><Icon size={19}/>{group.short}</figcaption></figure></div>{group.id==='licensing-legal'&&<p className="service-disclaimer">Licences, registrations and affiliations remain subject to the rules and approval of the relevant authorities. Prism Education provides guidance, documentation support and coordination.</p>}</div></section>}

export function ServicesFocused(){const[active,setActive]=useState(serviceGroups[0].id);useEffect(()=>{const observer=new IntersectionObserver(entries=>{const visible=entries.filter(x=>x.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(visible)setActive(visible.target.id)},{rootMargin:'-32% 0px -52%',threshold:[0,.15,.35]});serviceGroups.forEach(x=>{const el=document.getElementById(x.id);if(el)observer.observe(el)});return()=>observer.disconnect()},[]);return <><section className="relative isolate overflow-hidden bg-[#10263f] py-20 text-white md:py-28"><img src="/images/prism-hero.png" alt="" className="absolute inset-0 -z-20 h-full w-full object-cover opacity-30"/><div className="absolute inset-0 -z-10 bg-gradient-to-r from-[#10263f] via-[#10263f]/95 to-[#146b73]/70"/><div className="wrap"><p className="section-kicker !text-[#f3c35d]">PRISM EDU CONSULTANCY SERVICES</p><h1 className="mt-4 max-w-4xl text-[clamp(2.25rem,6vw,5rem)] font-extrabold leading-[1.04] tracking-[-.04em] text-white">Practical Services for Stronger Educational Institutions</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-white/75">From school planning, land and licensing to materials, technology and growth, Prism Education brings essential support services together on one platform.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to="/contact" className="btn">Request Consultation<ArrowRight size={16}/></Link><a href="#school-services" className="cta-outline">Explore Our Services</a></div></div></section><nav className="service-sticky-nav" aria-label="Service categories"><div className="service-sticky-inner">{serviceGroups.map(group=>{const Icon=group.icon;return <a key={group.id} href={'#'+group.id} className={'service-sticky-link '+(active===group.id?'is-active':'')} aria-current={active===group.id?'true':undefined}><Icon size={17}/>{group.short}</a>})}</div></nav>{serviceGroups.map((group,index)=><ServiceSection key={group.id} group={group} index={index}/>)}</>}

export const ServicesClosing=ServicesExperienceClosing;
